import { Inter } from "next/font/google";
import "./globals.css";
import { CartContextProvider } from "@/app/components/cart/cart-context";

const inter = Inter({ subsets: ["latin", "cyrillic"] });

export const metadata = {
  title: "Тестовое задание",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <CartContextProvider>{children}</CartContextProvider>
      </body>
    </html>
  );
}
